{
 "title": "TEZ",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "temp", "legendFormat": "approach = {{approach}}" }
   ]
  },
  {
   "title": "elderlySensor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "elderlySensor", "legendFormat": "approach = {{approach}}" }
   ]
  },
  {
   "title": "Temp 1/2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "temp1_2", "legendFormat": "approach = {{approach}}" }
   ]
  },
  {
   "title": "elderlySensor1_2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "elderlySensor1_2", "legendFormat": "approach = {{approach}}" }
   ]
  },
  {
   "title": "Temperature Dataset 1/4",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "temp1_4", "legendFormat": "approach = {{approach}}" }
   ]
  },
  {
   "title": "elderlySensor1_4",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "elderlySensor1_4", "legendFormat": "approach = {{approach}}" }
   ]
  }
 ]
}